### ISSUE TITLE
Peek feature yields unreadable highlight

### ISSUE THREAD

**Issue by gagbo** [bpruitt-goddard/vscode-sourcerer#4]
I'm in a C project if it's necessary : 

![](https://i.imgur.com/lOpc3JC.png)

I am currently "peeking" the exact same zone in the code, the highlight makes it hard to read the symbol.
I can provide further information if you ask. I'd like to help and propose a PR, but I have really no idea where to start

**Comment by gagbo** [comment]
I found the [relevant documentation](https://code.visualstudio.com/docs/getstarted/theme-color-reference#_peek-view-colors) with the keys you want to change to customize the Peek view.

The key you want to change is `peekViewEditor.matchHighlightBackground` (give or take a few caps), I got enough motivation to publish my own theme to make quick customizations now (and I used your repo as a base thanks) ; just to say that I am not listing the method to nag about the update, really just to help.

**Comment by bpruitt-goddard** [comment]
Sorry I was so late on this, I didn't get any notification. I fixed this as part of PR #5 and just pushed out the update. Thanks for pointing me to the right property!
